#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Andrew C. Dvorak

# Short bio or description (displayed in the header)
description: Software Engineer at Google

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: //gravatar.com/avatar/5c03500560d9632f2e09181de310e4cf?s=70

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: andy@andydvorak.net
  facebook:
  flickr:
  github: acdvorak
  instagram:
  linkedin: acdvorak
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: acdvorak
  stackoverflow: users/467582/andy-dvorak
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: +AndrewDvorak


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-16044220-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://blog.andydvorak.net

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to un-minify using :expanded

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
